version: 2

macros:
  - name: get_days_from_hours
    description: Convert hours to days.
    arguments:
      - name: hours
        description: Number of hours.
        type: integer

  - name: format_transaction_type
    description: Macro transaction type
    arguments:
      - name: column
        description: column for transaction_type
        type: text

  - name: calculate_response_rate
    description: calculate_response_rate
    arguments:
      - name: success_column
        description: column for sucessful transactions
        type: numeric
      - name: total_column
        description: column for total offers sent
        type: numeric

  - name: response_rate_valid
    description: validation of response rate
